# -*- coding: utf-8 -*-
"""ML mid project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119EFx9OTKxmiidELr3fIFmzgIs3bO9Qd

Step 1 – Install & Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc, f1_score, precision_score, recall_score

print("All libraries imported successfully!")

""" Step 2 – Create Custom Dataset"""

np.random.seed(42)
n = 500

study_hours   = np.round(np.random.uniform(0, 10, n), 1)
attendance    = np.round(np.random.uniform(40, 100, n), 1)
prev_gpa      = np.round(np.random.uniform(1.5, 4.0, n), 2)
assignments   = np.random.randint(0, 11, n)
sleep_hours   = np.round(np.random.uniform(4, 10, n), 1)
internet_hrs  = np.round(np.random.uniform(0, 8, n), 1)
part_time_job = np.random.choice([0, 1], n, p=[0.65, 0.35])
gender        = np.random.choice(["Male", "Female"], n)
department    = np.random.choice(["CS", "Business", "Engineering", "Arts"], n)

score = (study_hours*3 + attendance*0.4 + prev_gpa*10 +
         assignments*2 - internet_hrs*1.5 - part_time_job*3 + sleep_hours*0.5)
noise  = np.random.normal(0, 5, n)
passed = ((score + noise) >= np.median(score + noise)).astype(int)

df = pd.DataFrame({
    "study_hours": study_hours, "attendance": attendance,
    "prev_gpa": prev_gpa, "assignments": assignments,
    "sleep_hours": sleep_hours, "internet_hrs": internet_hrs,
    "part_time_job": part_time_job, "gender": gender,
    "department": department, "passed": passed
})

print("Dataset shape:", df.shape)
df.head()

Step 3 – Basic EDA

# Shape and data types
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)

# Missing values
print("\nMissing Values:\n", df.isnull().sum())

# Descriptive statistics
print("\nDescriptive Stats:")
df.describe()

""" Step 4 – EDA Visualizations"""

# Histogram of numeric features by pass/fail
num_cols = ["study_hours", "attendance", "prev_gpa", "assignments", "sleep_hours", "internet_hrs"]

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
fig.suptitle("Feature Distribution – Pass vs Fail", fontsize=14)

for ax, col in zip(axes.flat, num_cols):
    ax.hist(df[df["passed"]==0][col], bins=20, alpha=0.6, label="Fail", color="red")
    ax.hist(df[df["passed"]==1][col], bins=20, alpha=0.6, label="Pass", color="blue")
    ax.set_title(col)
    ax.legend()

plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(9, 6))
corr = df.select_dtypes(include=np.number).corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

# Pass rate by department
dept_pass = df.groupby("department")["passed"].mean() * 100
dept_pass.plot(kind="bar", color="steelblue", figsize=(7, 4))
plt.title("Pass Rate by Department (%)")
plt.ylabel("Pass Rate")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Box plots – key features vs pass/fail
fig, axes = plt.subplots(1, 4, figsize=(14, 4))
for ax, col in zip(axes, ["study_hours", "attendance", "prev_gpa", "internet_hrs"]):
    df.boxplot(column=col, by="passed", ax=ax)
    ax.set_title(col)
    ax.set_xlabel("0 = Fail, 1 = Pass")
plt.suptitle("")
plt.tight_layout()
plt.show()

"""Step 5 – Preprocessing"""

le = LabelEncoder()
df_enc = df.copy()
df_enc["gender"]     = le.fit_transform(df["gender"])
df_enc["department"] = le.fit_transform(df["department"])

X = df_enc.drop("passed", axis=1)
y = df_enc["passed"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print("Train size:", X_train.shape[0])
print("Test size :", X_test.shape[0])

"""Step 6 – Algorithm 1: Logistic Regression"""

lr = LogisticRegression(max_iter=500, random_state=42)
lr.fit(X_train_sc, y_train)

y_pred_lr  = lr.predict(X_test_sc)
y_proba_lr = lr.predict_proba(X_test_sc)[:, 1]

print("=== Logistic Regression ===")
print(f"Accuracy  : {accuracy_score(y_test, y_pred_lr)*100:.2f}%")
print(f"Precision : {precision_score(y_test, y_pred_lr)*100:.2f}%")
print(f"Recall    : {recall_score(y_test, y_pred_lr)*100:.2f}%")
print(f"F1 Score  : {f1_score(y_test, y_pred_lr)*100:.2f}%")
print(f"CV Score  : {cross_val_score(lr, X_train_sc, y_train, cv=5).mean()*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr, target_names=["Fail","Pass"]))

"""Step 7 – Algorithm 2: Random Forest"""

rf = RandomForestClassifier(n_estimators=150, max_depth=8, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf  = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

print("=== Random Forest ===")
print(f"Accuracy  : {accuracy_score(y_test, y_pred_rf)*100:.2f}%")
print(f"Precision : {precision_score(y_test, y_pred_rf)*100:.2f}%")
print(f"Recall    : {recall_score(y_test, y_pred_rf)*100:.2f}%")
print(f"F1 Score  : {f1_score(y_test, y_pred_rf)*100:.2f}%")
print(f"CV Score  : {cross_val_score(rf, X_train, y_train, cv=5).mean()*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf, target_names=["Fail","Pass"]))

"""TRAIN vs TEST ACCURACY COMPARISON"""

# ═══════════════════════════════════════════
#   TRAIN vs TEST ACCURACY COMPARISON
# ═══════════════════════════════════════════

# Logistic Regression
lr_train_acc = lr.score(X_train_sc, y_train) * 100
lr_test_acc  = lr.score(X_test_sc,  y_test)  * 100

# Random Forest
rf_train_acc = rf.score(X_train, y_train) * 100
rf_test_acc  = rf.score(X_test,  y_test)  * 100

# Print Results
print("="*45)
print("   Train vs Test Accuracy Comparison")
print("="*45)
print(f"{'Model':<22} {'Train':>10} {'Test':>10}")
print("-"*45)
print(f"{'Logistic Regression':<22} {lr_train_acc:>9.2f}% {lr_test_acc:>9.2f}%")
print(f"{'Random Forest':<22} {rf_train_acc:>9.2f}% {rf_test_acc:>9.2f}%")
print("="*45)

# Overfitting Check
print("\nOverfitting Check:")
if lr_train_acc - lr_test_acc > 10:
    print("Logistic Regression : ⚠️ Overfitting")
else:
    print("Logistic Regression : ✅ Balanced")

if rf_train_acc - rf_test_acc > 10:
    print("Random Forest       : ⚠️ Overfitting")
else:
    print("Random Forest       : ✅ Balanced")

Step 8 – Confusion Matrice

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, y_pred, title in zip(axes,
                              [y_pred_lr, y_pred_rf],
                              ["Logistic Regression", "Random Forest"]):
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Fail","Pass"],
                yticklabels=["Fail","Pass"], ax=ax)
    ax.set_title(f"Confusion Matrix – {title}")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.tight_layout()
plt.show()

Step 10 – Metrics Comparison Bar Chart

metrics = ["Accuracy", "Precision", "Recall", "F1 Score"]
lr_scores = [
    accuracy_score(y_test, y_pred_lr),
    precision_score(y_test, y_pred_lr),
    recall_score(y_test, y_pred_lr),
    f1_score(y_test, y_pred_lr)
]
rf_scores = [
    accuracy_score(y_test, y_pred_rf),
    precision_score(y_test, y_pred_rf),
    recall_score(y_test, y_pred_rf),
    f1_score(y_test, y_pred_rf)
]

x = np.arange(len(metrics))
w = 0.35

plt.figure(figsize=(9, 5))
plt.bar(x - w/2, [s*100 for s in lr_scores], w, label="Logistic Regression", color="steelblue")
plt.bar(x + w/2, [s*100 for s in rf_scores], w, label="Random Forest",       color="tomato")
plt.xticks(x, metrics)
plt.ylabel("Score (%)")
plt.ylim(0, 110)
plt.title("Model Performance Comparison")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

""" Step 11 – Feature Importance (Random Forest)"""

importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values()
importances.plot(kind="barh", figsize=(8, 5), color="tomato")
plt.title("Feature Importances – Random Forest")
plt.xlabel("Importance Score")
plt.tight_layout()
plt.show()

""" Step 12 – Final Summary & Analysis"""

print("=" * 50)
print("       FINAL MODEL COMPARISON SUMMARY")
print("=" * 50)
print(f"{'Metric':<15} {'Logistic Reg':>15} {'Random Forest':>15}")
print("-" * 50)

for metric, lr_s, rf_s in zip(metrics, lr_scores, rf_scores):
    print(f"{metric:<15} {lr_s*100:>14.2f}% {rf_s*100:>14.2f}%")

print("=" * 50)
print("""
CONCLUSION:
- Logistic Regression wins on Accuracy, Precision, F1
- This is because the pass/fail boundary is mostly LINEAR
  (it's a weighted sum of study hours, GPA, attendance)
- Random Forest adds complexity but no extra gain here
- LR is also faster, interpretable, and more stable

KEY INSIGHT FROM EDA:
- study_hours, prev_gpa, attendance → strongest predictors
- internet_hrs, part_time_job       → negatively impact results
- Department & gender               → minor effect
""")